beansmile/jianggaowang

Gemfile, Gemfile.lock, app/assets/javascripts/mobile.js, app/assets/javascripts/mobile/slides.js.coffee, app/assets/stylesheets/mobile.css, app/assets/stylesheets/mobile/slides.css.scss, app/controllers/application_controller.rb, app/controllers/slides_controller.rb, app/views/layouts/mobile.html.erb, app/views/slides/show.html+phone.erb, config/initializers/assets.rb, vendor/assets/javascripts/jquery.lazyload.js
https://trello.com/c/nXsT2EEY/19-list
=> using slides list in mobile devices

.gitignore, Gemfile, Gemfile.lock, README.md, app/controllers/slides_controller.rb, app/helpers/application_helper.rb, app/jobs/slide_convert_job.rb, app/models/preview.rb, app/models/slide.rb, app/uploaders/attachment_uploader.rb, app/uploaders/pdf_uploader.rb, app/uploaders/preview_uploader.rb, app/views/slides/_manual_actions.html.erb, app/views/slides/_pages.html.erb, app/views/slides/new.html.erb, app/views/slides/show.html+phone.erb, app/views/slides/show.html.erb, config/application.rb, db/migrate/20151208134903_add_file_to_slides.rb, db/migrate/20151208153414_add_file_to_previews.rb, db/schema.rb, lib/pdf_converter.rb
实现新的 PDF 上传、转换等一系列流程，不再依赖七牛。
1. 文档上传后异步处理转换；
2. 文档转换后分辨率提升到 DPI 为 150，确保图片画质，Retina 屏幕全屏下不再有模糊感；
3. 仍旧支持不同尺寸缩略图，优化列表页加载性能。
0. 服务器上部署前需记得务必安装 GhostScript 以及 ImageMagick，以及完成后面提到的脚本的编写；
1. 编写脚本，对原来的讲稿都重新进行转换保存，以便统一使用新的机制；
2. 重新从产品层面设计上传的交互流程；
3. 清理原来跟七牛相关的代码；
4. 头像目前还是用着七牛的 bucket，后续考虑是否保留这个功能。
=> Implement new processing flow

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/frontend/richtext_editor.js, app/assets/stylesheets/application.css, app/views/events/_form.html.erb, app/views/events/show.html.erb
- use wysihtml5 to edit event content
@ZedZhang
=> Use richtext editor for event content

app/assets/javascripts/frontend/richtext_editor.js, lib/pdf_converter.rb
- optimise the code for rich text editor
- add map and memory limit to protect being killed
=> Hotfix convert

app/views/slides/show.html.erb
=> hide the collection button

app/assets/stylesheets/frontend/events.css.scss
hotfix the modal for showing the dialog of inserting a image and link
=> hot fix insert link and image for a event

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb
when the request are come from these controller: UserPasswordsController SessionsController UsersController, do not set the path in sessions
=> fix the redirect path for after sign in

app/models/event.rb
`  has_many :slides, dependent: :destroy`
=> add dependent for event

db/migrate/20151223023726_change_slides_description.rb, db/schema.rb
change slide description from string to text
=> Hotfix sldies description

config/secrets.yml.example
Fix the secrets.yml without a semicolon .
=> Fix the secrets.yml without a semicolon

app/admin/user.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/sessions/new.html.erb, app/views/shared/_footer.html.erb, app/views/users/new.html.erb, config/routes.rb, db/migrate/20160405091551_add_approved_at_to_users.rb, db/schema.rb, lib/tasks/hotfix.rake
=> User sign up

app/models/slide.rb, app/uploaders/audio_uploader.rb, db/migrate/20160406094331_add_audio_to_slides.rb, db/schema.rb
=> Add audio filed

app/assets/stylesheets/frontend/_variable.scss, app/assets/stylesheets/frontend/common.scss, app/assets/stylesheets/jianggaowang.css
=> Reconstruction-css-file

.eslintrc.json, .gitignore, .stylelintrc, README.md, package.json
Use the EsLint and StyleLint to check the code styles with the recommend rules.
=> Add eshint and stylelint

app/mailers/user_password_mailer.rb, config/initializers/smtp.rb
https://trello.com/c/t2bX04wL/42-2-update-email-notification
=> Update email notification

app/views/sessions/new.html.erb
Remove the “</a>” in user-toggle.
=> Remove the “</a>” in user-toggle.

app/assets/stylesheets/frontend/_variables.scss, app/assets/stylesheets/frontend/cards.scss, app/assets/stylesheets/frontend/groups.scss, app/assets/stylesheets/frontend/pagination.scss, app/assets/stylesheets/frontend/search_tips.scss, app/assets/stylesheets/frontend/tags.scss, app/assets/stylesheets/jianggaowang.css, app/controllers/home_controller.rb, app/views/home/static_page.html.erb, config/routes.rb
=> Refactor pagination and tags

app/controllers/events_controller.rb, app/controllers/home_controller.rb, app/controllers/slides_controller.rb, app/models/slide.rb, app/views/home/index.html.erb, app/views/slides/_slide_item.html.erb, config/routes.rb
=> Integrate homepage with new design

app/controllers/users_controller.rb
https://trello.com/c/ZldDSzNz/49-0-5-should-not-visit-signup-page-if-user-has-login
=> Should not visit signup page if user has login

README.md
README 文档原来有个地方格式不是很好，序号不对：
求合并，repo主好人一生平安！
=> optimize the README content formats

app/views/events/index.html.erb, app/views/kaminari/_first_page.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/shared/_header.html.erb, config/initializers/kaminari_config.rb, config/locales/kaminari.zh-CN.yml
https://trello.com/c/WdRQG6Md/50-2-integrate-events-page-with-new-design
=> Integrate events page with new design

app/controllers/events_controller.rb, app/controllers/slides_controller.rb, app/views/events/index.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/slides/index.html.erb
https://trello.com/c/34JvBa5u/51-2-integrate-slides-page-with-new-design
=> Integrate slides page with new design

app/assets/stylesheets/framework.css, app/assets/stylesheets/frontend/common.scss, app/assets/stylesheets/frontend/users.scss, app/assets/stylesheets/jianggaowang.css, vendor/assets/stylesheets/reset.css
=> Hotfix login register page

app/assets/stylesheets/frontend/common.scss, app/models/event.rb, app/views/events/show.html.erb, db/migrate/20160414072829_add_venue_to_events.rb, db/schema.rb
https://trello.com/c/WOgfxXG4/52-integrate-event-details-page-with-new-design
=> Integrate event details page with new design

app/assets/stylesheets/frontend/event_details.scss, app/assets/stylesheets/frontend/groups.scss, app/assets/stylesheets/frontend/select_event.scss, app/assets/stylesheets/frontend/tags.scss, app/assets/stylesheets/jianggaowang.css, app/views/events/show.html.erb, app/views/home/static_page.html.erb, app/views/slides/index.html.erb
=> reafctored select event bar

app/assets/stylesheets/frontend/header.scss, app/helpers/application_helper.rb, app/helpers/users_helper.rb, app/views/shared/_guest_user_navbar_items.html.erb, app/views/shared/_header.html.erb, app/views/shared/_sign_up_in_tab.html.erb
https://trello.com/c/aX8jWzaQ/56-0-5-highlight-current-page-in-header
=> Highlight current page in header

app/assets/javascripts/framework.js, app/assets/javascripts/frontend/events.js, app/assets/stylesheets/framework.css, app/views/events/new.html.erb, vendor/assets/javascripts/jquery.datetimepicker.full.js, vendor/assets/stylesheets/jquery.datetimepicker.css
Add jQuery.datetimepicker plugin for events new page.
=> Add jQuery.datetimepicker plugin for events new page.

app/assets/javascripts/frontend/common.js, app/assets/javascripts/frontend/events.js, app/assets/javascripts/frontend/profile.js, app/assets/stylesheets/frontend/profile_edit.scss, app/views/profiles/edit.html.erb
以下两个页面上传图片的功能调用的都是同一段代码：
创建活动页面：
个人资料页面：
=> Take the common function for upload cover and upload avatar.

app/assets/stylesheets/frontend/file_upload.scss, app/assets/stylesheets/frontend/form_common.scss, app/views/events/new.html.erb, app/views/slides/new.html.erb
创建活动页面：
PC:
Tablet:
Mobile:
上传讲稿页面：
PC:
Tablet:
Mobile:
=> Add responsive for events new page and slides page

app/assets/javascripts/frontend/carousel.js, app/assets/javascripts/frontend/common.js, app/assets/javascripts/frontend/header.js, app/assets/javascripts/jianggaowang.js, app/assets/stylesheets/frontend/_variables.scss, app/assets/stylesheets/frontend/cards.scss, app/assets/stylesheets/frontend/carousel.scss, app/assets/stylesheets/frontend/common.scss, app/assets/stylesheets/frontend/event_details.scss, app/assets/stylesheets/frontend/file_upload.scss, app/assets/stylesheets/frontend/footer.scss, app/assets/stylesheets/frontend/header.scss, app/assets/stylesheets/frontend/pagination.scss, app/assets/stylesheets/frontend/panel.scss, app/assets/stylesheets/frontend/search_tips.scss, app/assets/stylesheets/frontend/select_event.scss, app/assets/stylesheets/frontend/slides.scss, app/assets/stylesheets/frontend/tags.scss, app/assets/stylesheets/jianggaowang.css, app/views/events/index.html.erb, app/views/events/new.html.erb, app/views/events/show.html.erb, app/views/home/index.html.erb, app/views/home/static_page.html.erb, app/views/profiles/edit.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, app/views/slides/index.html.erb, app/views/slides/new.html.erb
=> Enable responsive for mobile

app/assets/stylesheets/frontend/cards.scss, app/assets/stylesheets/frontend/carousel.scss, app/assets/stylesheets/frontend/common.scss, app/assets/stylesheets/frontend/header.scss, app/assets/stylesheets/frontend/panel.scss, app/assets/stylesheets/frontend/slides.scss, app/views/events/_event_item.html.erb, app/views/home/static_page.html.erb, app/views/shared/_guest_user_navbar_items.html.erb, app/views/shared/_header.html.erb, app/views/shared/_signed_in_user_navbar_items.html.erb, app/views/slides/_slide_item.html.erb
=> Enable responsive for tablet

app/assets/stylesheets/frontend/profile_edit.scss, app/views/profiles/edit.html.erb
个人资料页面响应式：
PC端：
Tablet：
Mobile:
=> Add responsive person data page.

app/assets/stylesheets/frontend/sessions.css.scss, app/assets/stylesheets/frontend/site.css.scss, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb
=> hotfixed the footer position

app/assets/stylesheets/frontend/site.css.scss
https://trello.com/c/7iUy7CTa/75-footer-slide
=> hotfixed the footer position under the full screen state

app/assets/javascripts/framework.js, app/assets/javascripts/framework/jquery.noty-config.js.coffee, app/assets/javascripts/frontend/messages.coffee, app/assets/javascripts/jianggaowang.js, app/assets/stylesheets/frontend/users.scss, app/controllers/sessions_controller.rb, vendor/assets/stylesheets/animate.css
https://trello.com/c/lEavdZ5I/54-2-show-login-flash-messages
=> Show login flash messages

app/views/events/index.html.erb, app/views/home/index.html.erb, app/views/slides/index.html.erb
https://trello.com/c/5h6Bjhvl/76-0-5
=> 没有讲稿/活动的提示文字被压缩

.gitignore, app/controllers/events_controller.rb, app/controllers/home_controller.rb, app/controllers/profiles_controller.rb, app/models/event.rb, app/views/profiles/events.html.erb, app/views/profiles/show.html.erb, app/views/profiles/slides.html.erb, config/routes.rb
https://trello-attachments.s3.amazonaws.com/57203607f47ddb210ab8e635/1321x1432/c249ee595cbe4344d0d59068451043f4/jianggaowang-profile-page.png
=> modify the profile page

app/admin/event.rb, app/controllers/home_controller.rb, app/models/event.rb, app/views/home/index.html.erb, config/locales/models.zh-CN.yml, db/migrate/20160428091239_add_attrs_to_events.rb, db/schema.rb
=> Add events carousel figure on home page

Gemfile, Gemfile.lock, config/environments/production.rb, config/environments/staging.rb, config/secrets.yml.example
https://trello.com/c/PsODUyCd/78-0-5-remove-sutui-configutation
=> Remove sutui configutation

app/assets/stylesheets/frontend/cards.scss, app/assets/stylesheets/frontend/common.scss, app/assets/stylesheets/frontend/footer.scss, app/assets/stylesheets/frontend/header.scss, app/assets/stylesheets/frontend/slides.scss, app/views/shared/_footer.html.erb
1. header上文字的字宽偏大
2. 每个讲稿card的边框和投影的渲染有问题
3. 每个讲稿card的圆角缺失
4. footer的margin-top的距离少了10px
5. 登陆和注册页面的是没有header的，并且footer样式不正确
6. 每个讲稿文字说明部分的行间距不正确
7. 搜索输入框的圆角数据不正确：实现为4px，设计稿为2px
PS：合并前麻烦让 danny 再次确认一下。
=> UI QA hotfixed

app/assets/javascripts/frontend/form_verify.js, app/assets/javascripts/jianggaowang.js, app/assets/stylesheets/frontend/common.scss, app/assets/stylesheets/frontend/users.scss, app/controllers/sessions_controller.rb, app/controllers/user_passwords_controller.rb, app/controllers/users_controller.rb, app/views/layouts/sign_in_up.html.erb, app/views/sessions/new.html.erb, app/views/users/new.html.erb
=> Modify login signup page

app/assets/stylesheets/frontend/file_upload.scss
=> This fixes #126 , modify the ui bug on the new-slides/new-events page

app/controllers/events_controller.rb, app/views/events/_event_item.html.erb, app/views/events/choose.html.erb, app/views/shared/_signed_in_user_navbar_items.html.erb, config/routes.rb
=> choose event before new slide

app/controllers/concerns/search_controller.rb, app/controllers/events_controller.rb, app/controllers/slides_controller.rb, app/models/event.rb, app/models/slide.rb, app/views/events/search.html.erb, app/views/events/show.html.erb, app/views/search/index.html.erb, app/views/shared/_header.html.erb, app/views/shared/_search_tips_header.html.erb, config/routes.rb
https://trello.com/c/ez36AhfS/64-3-search-slides-and-events
=> Search slides and events

Gemfile, Gemfile.lock, app/controllers/tags_controller.rb, app/models/slide.rb, app/views/shared/_header.html.erb, app/views/tags/index.html.erb, config/routes.rb, db/migrate/20160503065236_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb, db/migrate/20160503065237_add_missing_unique_indices.acts_as_taggable_on_engine.rb, db/migrate/20160503065238_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb, db/migrate/20160503065239_add_missing_taggable_index.acts_as_taggable_on_engine.rb, db/migrate/20160503065240_change_collation_for_tag_names.acts_as_taggable_on_engine.rb, db/schema.rb
=> Slides tags index page

app/controllers/slides_controller.rb, app/views/slides/tagged.html.erb, app/views/tags/index.html.erb, config/routes.rb
https://trello.com/c/WvlN1XIy/73-2-slides-of-tag-show-page
=> Slides of tag show page

app/assets/stylesheets/frontend/slides.scss
=> modify the slides carousel button style

config/secrets.yml.example
https://trello.com/c/kr3wJt6C/91-0-5-make-secrets-yml-example-safe
=> Make secrets.yml.example safe

app/controllers/events_controller.rb, app/models/event.rb, config/locales/models.zh-CN.yml
https://trello.com/c/O4YLfhBY/95-1-add-validation-to-event-model
=> Add validation to event model

app/controllers/events_controller.rb, app/models/event.rb, app/views/events/edit.html.erb, app/views/events/new.html.erb, config/locales/models.zh-CN.yml
https://trello.com/c/K3vtUGav/97-1-add-venue-text-field-when-creating-editing-events
=> Add venue text field when creating/editing events

app/controllers/slides_controller.rb, app/models/slide.rb, app/views/slides/_recommended_slides.html.erb, app/views/slides/show.html.erb
https://trello.com/c/8z3v4WpR/74-5-recommend-slides
=> Recommend slides

config/locales/kaminari.zh-CN.yml
https://trello.com/c/JxplxS80/101-0-5-update-pagination-truncate-of-kaminari
=> Update pagination truncate of Kaminari

app/controllers/tags_controller.rb, app/views/tags/show.html.erb
https://trello.com/c/2ksnSRAZ/100-2-slides-of-tags-show-page
=> Slides of tags show page

app/views/events/show.html.erb, config/application.rb, lib/content_scrubber.rb
https://trello.com/c/XpBWpxkK/105-1-modify-sanitize-method-to-show-rich-text-correctly
=> Modify sanitize method to show rich text correctly

app/assets/stylesheets/frontend/article.scss
for the event details intro under the firefox
=> hot fixed the work break

app/models/concerns/disqus_concern.rb, app/models/event.rb, app/models/slide.rb, app/views/events/show.html.erb, app/views/shared/_disqus.html.erb, app/views/slides/show.html.erb, config/secrets.yml.example
=> add disqus to events and slides

app/assets/stylesheets/frontend/slides.scss, app/controllers/events_controller.rb, app/models/event.rb, app/models/slide.rb, app/views/events/_recommended_events.html.erb, app/views/events/show.html.erb, app/views/home/static_page.html.erb, lib/tasks/hotfix.rake
https://trello.com/c/5zPtEIQQ/121-3-add-recommended-events-on-event-show-page
=> Add recommended events on event show page

app/assets/stylesheets/frontend/slides.scss, app/views/slides/_manual_actions.html.erb, app/views/slides/show.html.erb
=> prettify error info in slide show page

app/assets/stylesheets/frontend/file_upload.scss, app/views/events/edit.html.erb, app/views/events/new.html.erb, app/views/slides/_form.html.erb
117-1-upload-button-should-change-cursor-style-when-hover
=> Upload button should change cursor style when hover

app/views/slides/show.html.erb, config/routes.rb
https://trello.com/c/qitsWGwY/134-1-hide-like-and-collect-button
=> Hide like and collect button

app/assets/stylesheets/frontend/cards.scss
https://trello.com/c/mPyW4R9l/135--
=> 推荐讲稿应该加个边框(safari)

app/assets/stylesheets/frontend/profile_edit.scss, app/views/profiles/edit.html.erb
=> fix verify-btn overlap with label

app/controllers/tags_controller.rb
https://trello.com/c/7v9z2iwA/142-1-should-not-list-tags-which-don-t-has-any-slides
=> Should not list tags which don't has any slides

public/404.html
https://trello.com/c/mtnKI2Bs/146-1-404
=> 使用腾讯公益宝贝回家 404 页面

app/assets/stylesheets/frontend/slides.scss
=> change audio tag to be full width

app/controllers/slides_controller.rb, app/models/user.rb
https://trello.com/c/YPSCgWFG/161-1-move-model-logic-from-slides-controller-into-slide-model
=> Move model logic from slides_controller into slide model

lib/pdf_converter.rb
https://trello.com/c/BrcZlQJq/172--
=> Limit memory in converting PDF to images

app/views/events/show.html.erb
=> 活动页面的评论应该是放在最下方

app/views/sessions/new.html.erb, app/views/users/new.html.erb
=> 登录页和注册页没有去首页的链接

app/assets/stylesheets/frontend/slides.scss, app/controllers/slides_controller.rb, app/views/slides/show.html.erb, config/routes.rb
https://trello.com/c/ZGXi7ioP/163-1-download-pdf-file
=> Download PDF file

config/application.rb
https://trello.com/c/cYcMYYp7/184-0-5-tag-app-version-to-be-v2-1-0
=> Tag app version to be v2.1.0

config/sidekiq.yml
https://trello.com/c/mp2oNvIQ/186-0-5-set-concurrency-of-sidekiq-to-be-5
=> Set concurrency of sidekiq to be 5

config/routes.rb
=> disable users#show route entrance

app/assets/javascripts/frontend/app.js, app/assets/stylesheets/frontend/common.scss
=> enable turbolinks progress bar for jianggaowang

app/views/slides/_slide.html.erb
https://trello.com/c/veektDPQ/187--
On the reconstruction of individual pages, re-modification
=> 废弃的个人页面导致页面混乱

app/views/users/show.html.erb
https://trello.com/c/erflpa87/189-2
friendly display information when users haven't lecture
=> 189-no-lecture-display-null

app/models/event.rb
https://trello.com/c/vKSCCWTc/194-jianggaowang-exception-events-create-nomethoderror-undefined-method-for-nil-nilclass
=> [Jianggaowang Exception]events#create (NoMethodError) "undefined method `<' for nil:NilClass"

config/application.rb, lib/block_bad_spider.rb
https://trello.com/c/FdOvlrsZ/190-jianggaowang-exception-slides-create-actioncontroller-invalidauthenticitytoken-actioncontroller-invalidauthenticit
=> [Jianggaowang Exception]slides#create (ActionController::InvalidAuthenticityToken)

app/admin/feedback.rb, app/assets/stylesheets/frontend/feedbacks.scss, app/assets/stylesheets/frontend/file_upload.scss, app/assets/stylesheets/jianggaowang.css, app/controllers/feedbacks_controller.rb, app/models/feedback.rb, app/views/feedbacks/new.html.erb, app/views/shared/_footer.html.erb, config/locales/models.zh-CN.yml, config/routes.rb, db/migrate/20161015023608_create_feedbacks.rb, db/schema.rb
=> 增加意见反馈功能，方便收集用户反馈

app/controllers/application_controller.rb
[Jianggaowang Exception]home#index (ActionView::MissingTemplate) 
https://trello.com/c/rklWByYs/201-jianggaowang-exception-home-index-actionview-missingtemplate-missing-template-home-index-application-index-with
=> [Jianggaowang Exception]home#index (ActionView::MissingTemplate) 
